# Generated by Django 4.2 on 2025-06-04 20:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_place_remove_order_lat_remove_order_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.place', verbose_name='координаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 6, 4, 20, 44, 47, 355945, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
