# Generated by Django 4.2 on 2025-05-29 19:15

from django.db import migrations


def fill_prices(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')

    items = OrderItem.objects.filter(price__isnull=True).select_related('product')

    for item in items:
        item.price = item.product.price
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(fill_prices),
    ]
