# Generated by Django 4.2 on 2025-05-30 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_called_at_order_created_at_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличностью'), ('card', 'Электронно')], db_index=True, default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 5, 30, 19, 25, 43, 600558, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
