# Generated by Django 4.2 on 2025-06-04 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_lat_order_lon_alter_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='адрес')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='долгота')),
            ],
            options={
                'verbose_name': 'координаты',
                'verbose_name_plural': 'координаты',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='lon',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 6, 4, 20, 7, 39, 427334, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
